create table scenic_spot
(
    id              bigint auto_increment comment '景点ID'
        primary key,
    name            varchar(200)                       not null comment '景点名称',
    description     text                               null comment '景点描述',
    longitude       decimal(10, 7)                     null comment '经度',
    latitude        decimal(10, 7)                     null comment '纬度',
    address         varchar(500)                       null comment '详细地址',
    image_url       text                               null comment '景点图片URL列表(JSON数组)',
    image_anime_url text                               null comment '动漫风格图片URL列表(JSON数组)',
    video_url       text                               null comment '景点视频URL',
    region          varchar(50)                        not null comment '所属区域',
    created_at      datetime default CURRENT_TIMESTAMP null comment '创建时间',
    updated_at      datetime default CURRENT_TIMESTAMP null on update CURRENT_TIMESTAMP comment '更新时间'
)
    comment '景点表' charset = utf8mb4;

INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (1, '大明湖', '始建于北魏，历代重修扩建；杜甫、李邕曾游宴，有"济南名士多"典故', 117.0158330, 36.6700000, '大明湖景区历下亭', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/大明湖_实景_01.jpg', null, null, '济南', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (2, '趵突泉', '始建于北魏，宋代始建亭，历代重修；乾隆御封"天下第一泉"，为济南三大名胜之一', 117.0116670, 36.6630560, '趵突泉景区观澜亭', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/趵突泉_实景_01.jpg', null, null, '济南', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (3, '千佛山', '古称历山，隋代凿佛建寺，历代扩建；佛教名山，济南三大名胜之一，有舜耕传说', 117.0083330, 36.6433330, '千佛山风景名胜区', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/千佛山_实景_01.jpg', null, null, '济南', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (4, '华不注山', '春秋已得名，为古济南名山；孤峰刺天，历代画家诗人题咏众多，赵孟頫《鹊华秋色》主角之一', 117.0866670, 36.7366670, '黄河南岸华山森林公园', null, null, null, '济南', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (5, '鹊山', '因扁鹊炼丹传说得名，为济南名山；与华不注并称鹊华，为赵孟頫《鹊华秋色》主角之一', 117.0166670, 36.7500000, '黄河北岸鹊山村', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/鹊山_实景_01.jpg', null, null, '济南', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (6, '汇波楼', '始建于元代，历代重修；汇波晚照为济南八景之一', 117.0180560, 36.6722220, '大明湖景区汇波楼', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/汇波楼_实景_01.jpg', null, null, '济南', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (7, '五龙潭', '隋唐已成名泉，历代修整；传说为秦琼故居，泉群汇为深潭', 117.0138890, 36.6658330, '五龙潭公园', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/五龙潭_实景_01.jpg', null, null, '济南', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (8, '珍珠泉', '金代已列入名泉志，明清为巡抚衙门驻地；泉沸如浮珍珠，为济南四大名泉之一', 117.0166670, 36.6669440, '珍珠泉大院', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/珍珠泉_实景_01.jpg', null, null, '济南', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (9, '黑虎泉', '金代已列入名泉，明代始建石龛；三兽喷黑水，声如虎啸，为济南四大名泉之一', 117.0208330, 36.6597220, '黑虎泉泉群', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/黑虎泉_实景_01.jpg', null, null, '济南', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (10, '华山', '古称华不注，春秋齐晋鞌之战发生于此；孤峰独秀，为济南胜景', 117.0866670, 36.7366670, '华不注山', null, null, null, '济南', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (11, '金线泉', '金代已列入名泉志，清代归并入趵突泉公园；水面有纹如金线，为济南四大名泉之一', 117.0122220, 36.6627780, '趵突泉公园内', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/金线泉_实景_01.jpg', null, null, '济南', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (12, '灵岩寺', '始建于东晋，唐代拓建，历代重修；海内四大名刹之首，有千佛殿辟支塔', 116.9666670, 36.3666670, '泰山西北灵岩寺景区', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/灵岩寺_实景_01.jpg', null, null, '济南', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (13, '龙洞', '北魏已见记载，为济南东名山；山川幽胜，有龙洞秋风为济南八景之一', 117.1166670, 36.6833330, '龙洞风景区', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/龙洞_实景_01.jpg', null, null, '济南', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (14, '泰山', '先秦至秦汉：先秦时期已成为五岳之首和政权象征，秦始皇统一六国后，将泰山祭祀仪式变为帝王专有的封禅大典。汉武帝曾先后8次前往岱顶封禅，汉光武帝也进行过一次泰山封禅。
魏晋南北朝：佛教和道教相继流入泰山，时局动荡使常规祭祀难以开展，临时的非常规祭祀盛行，分裂政权常祭祀泰山以证明统治合法性。
隋唐宋金：隋代开创泰山祭祀制度，将其纳入政府行政体系；唐代开创泰山封爵制度，并规范祭祀仪式程序。宋代宋真宗前往泰山封禅，此后皇帝不再正式举办封禅大典。金代泰山庙呈现道教化宫观化色彩。这一时期还出现了泰山书院。
元明清：元代加封泰山为“东岳为天齐大生仁圣帝”；明朝增设管理泰山的官员，文人墨客游览增多并留下墨迹；清朝康熙、乾隆等皇帝都曾前往泰山祭祀或游览。历代帝王均来泰山举行封禅大典。；黄河与泰山是齐鲁大地独一无二的地理坐标。黄河与泰山古有“河岳”之并称。从古至今，泰山和黄河从文化的点、线、面多个维度互动，蕴含静与动、阳与阴、时间与空间、责任与信仰的多重意象。
见证着华夏文明的形成和发展，映照出中华民族对和谐、安宁的千年追寻。主峰玉皇顶拔地而起，海拔1545米，如天柱般屹立。
泰山并非寻常山岳，而是华北克拉通古老基底的脊梁，其岩体形成于25亿年前的新太古代，历经五次构造运动隆升，终成“五岳独尊”。
地质上，泰山属于鲁西隆起带，而其北侧广袤的黄河下游平原则坐落在济阳坳陷之上，一隆一陷，一刚一柔。
二者在构造上互为镜像：山为骨，河为脉；山主静，河主动；山守恒，河创生。正是这种地质上的张力与互补，塑造了齐鲁“山河表里、刚柔相济”的独特格局。', 117.1086220, 36.2577770, '泰安市泰山', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/黄河与泰山同框_实景_03.jpg.jpg', null, null, '泰安', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (15, '黄河', '西晋时古黄河流经此地；陆机任平原内史时乘舟畅游黄河时做此诗，元吉降初巳。濯秽游黄河。此诗是诗人活动于德州黄河流域重要见证。', 116.3074280, 37.4539680, '德州市古黄河上', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/超然楼_实景_01.jpg', null, null, '德州', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (16, '无棣沟', '无棣沟，在今庆云县境内。史载春秋时齐国有无棣邑，隋朝置无棣县，唐代有古黄河流经。；无棣沟，是位于今河北省盐山县境内的一条古河道，古称无棣水（河），为清河支流，也是古黄河的支。其历史可追溯至春秋之前，春秋时即为齐国北部重要的鱼盐运输通道 。该河道在北朝魏时改称无棣沟。隋朝末年淤废，唐永徽元年（公元650年），沧州刺史薛大鼎曾主持疏浚以利鱼盐运输 。唐开元年间（公元723年）复经开挖。至元、明时期，无棣沟已基本湮灭。隋开皇六年（586年）置无棣县，即因县南临此沟而得名。', 117.3863500, 37.7761600, '德州市庆云县无棣沟', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/无棣沟-实景-01.jpg', null, null, '德州', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (17, '卫运河', '原为黄河故道，因春秋属卫地而得名，汉代称白沟。卫运河、南运河的前身为清河，为先秦黄河决流而成。历史上，卫河、卫运河、南运河是一条河，唐代称永济渠，宋代称御河。；卫运河（含卫河）上段是沟通河南、山东的重要航道，历史上大部分时间都为通航河段。是古黄河文化在德州重要见证。', 115.7839290, 36.9977760, '德州市夏津县卫运河', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/卫运河-实景-01.webp', null, null, '德州', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (18, '德州黄河号子', '起源可溯至明清至近代‌：德州因地处黄河故道与京杭大运河交汇处，船工拉纤、筑堤打硪（夯土）广泛使用号子协调劳作，
形式分“开船号”“起锚号”“扛船号”“打硪号”等，具“一领众和”结构，曲调高亢质朴，如《三朵花》《落莲花》。
‌清至民国持续发展‌：乾隆年间黄河治理工程中已有明确硪号记载；19世纪末至20世纪初，德州沿河（含齐河段）船工、
硪工群体稳定传唱，内容含劳动指令与即兴俚语。
‌20世纪中叶式微‌：1950–70年代，机械取代人力（如吸泥船“红心一号”1960年代启用、铁路航运兴起），拉纤与大硪集体劳动消失，号子实用功能消退，仅老匠人口传。
‌2008年起系统保护‌：德州地区夯硪号子被纳入国家级非遗“黄河号子”（项目编号Ⅱ-133，含河南、山东多地）；2010年代起，德州市文化馆、齐河县河务局及非遗传承人（如郑福明）开展搜集、展演进校园。
‌2022年正式命名“德州黄河号子”为市级非遗‌：明确以齐河沿黄区域为核心传承地，强调其区别于河南中牟等地的“打硪号子”，突出德州“河运+治黄”双重语境。‌；黄河号子是一种劳动号子，是船工和河工在劳动中喊唱的民间音乐形式 。2008年，黄河号子被公布为国家级非物质文化遗产。2021年11月，齐河县申报的传统音乐“黄河号子”入选山东省第五批省级非物质文化遗产代表性项目扩展名录。
黄河号子采用一领众和的形式，节奏铿锵，情绪激昂，用以协调人力、鼓舞劳动情绪。按照劳动工种和场景，主要分为河工号子、夯硪号子和船工号子。黄河号子不仅有指挥劳动的实用价值，也以其优美的旋律、独特的韵味成为黄河文化的重要组成部分。
黄河号子最早可追溯至春秋时期先民们在修堤夯土时发出的“杭”“育”之声，伴随着黄河治理与航运劳动而产生并传唱。据《宋史·河渠志》记载：“凡用丁夫数百或千人，杂唱齐挽，积置于卑薄之处，谓之‘埽岸’。”这种“杂唱”就是黄河号子。
   黄河号子采用“一人领、众人和”的领和形式，其节奏铿锵，情绪激昂，曲调敦厚质朴、雄劲开阔、高亢有力。按照劳动工种和场景，主要分为河工号子、夯硪号子和船工号子。河工号子又可细分为骑马号、绵羊号、小官号、花号等不同腔调，以及捆枕号子、推枕号子、打桩号子、搂厢号子等工作号子。号子产生并服务于集体劳动，具有指挥劳动、协调动作、鼓舞士气、放松情绪、减缓劳动强度的实用价值。紧张型与舒缓型号子交替使用，能有效调节劳动强度。号词大多根据生活和生产中的经验、常识编排而成，熟练时可即兴创作，朗朗上口，易于传唱。其内容取材广泛，既包括抢险施工技术、河工生活逸事，也包含百姓喜闻乐见的戏文故事（如王侯将相、才子佳人），蕴含丰富的传统文化内涵和技术通俗性。号子以高亢、浑厚、雄壮、有力的节奏和声音，通过喊唱、齐唱、呼喊等表现形式，展现出协作一致、群情激昂的情绪与干劲，具有强烈的艺术感染力 。', null, null, '德州市齐河县', null, null, null, '德州', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (19, '德州黑陶', '德州黑陶历史沿革：新石器时代龙山文化起源 → 商周后失传 → 20世纪70年代末在德州复原 → 1980年代命名崛起 → 2009年获“中国黑陶城”称号 → 2014年烧制技艺列入国家级非遗。‌
‌新石器时代晚期（约4500–4000年前）‌：属大汶口文化晚期至龙山文化时期，德州地区（如齐河、禹城等地）为龙山黑陶重要发祥地之一，以“蛋壳陶”（厚0.3–1.2毫米）为代表，具备“黑如漆、亮如镜、叩如磬”特征，采用快轮成型与封窑渗碳工艺，属祭祀礼器巅峰。
‌商至汉代‌：随着青铜器与早期瓷器兴起，黑陶制作渐衰，至汉代基本失传。
‌1928年‌：龙山文化因山东章丘城子崖遗址发掘被正式命名，但制作技艺仍未知；德州本地虽有黑陶残片出土（如尹屯、邢寨汪遗址），未形成连续传承。
‌1970年代末‌：德州市工艺美陶研究所（前身为1979年芦庄黑陶厂）在王宪利、寇维军等艺人带领下，以京杭大运河红胶泥为原料，手工复原龙山黑陶技法，突破蛋壳陶成型与硬刻工艺。
‌1986年‌：作品首次以“德州黑陶”名义在上海展出；1987年北京展览获谷牧题词“龙山新风”，引发全国黑陶热，作品被人民大会堂收藏并用作国礼。
现代发展‌：在传统“11道工序”（选材、拉坯、压光、雕刻、渗碳烧制等）基础上，融合硬刻、微雕、无釉开片等创新，衍生茶具、香薰、艺术陈设等品类，持续推动非遗活化与文旅融合。‌；德州黑陶是中国黑陶的一种，因出土于山东省德州市而得名，属大汶口文化晚期至龙山文化时期的代表性陶器，
距今约4000多年历史。其采用京杭大运河红胶泥为原料，经选材、拉坯、雕刻、烧制等11道工序制成，
具有“黑如漆、亮如镜、叩如磬”的特征，表面可运用阴刻、镂空等技法形成纹理。德州是现代中国黑陶的发源地，
是古代陶瓷的重要发源地之一，古代德州以发明“鬲”而闻名于世，称“有鬲氏”古代氏族部落以本部落发明而得名，
如“神农氏”“有巢氏”等，德州又是古龙山文化的重要发源地之一，以黑陶为代表的龙山文化是1928年首先在山东
章丘县龙山镇城子崖被发现，而中国首次发现的新文化类型以当地的地名命名，故山东黑陶得名龙山文化。在德州的齐河、
禹城、乐陵、庆云、德城区发现这一时期的文化遗址有20多处德城区（在陈公堤口村西边铁路桥洞铁路东面北300米的水沟
南侧发现）并出土了大量的文物有鬲、盆、罐、杯等，其中最典型的是被称为龙山文化典型代表的蛋壳陶杯（蛋壳陶手工在陶车上手拉坯制成，其厚0.3-1.2毫米，薄如蛋壳而得名），蛋壳陶杯是当时的最高级的祭祀礼器，也是古今拉坯制陶的最高水平，
蛋壳陶的出现表示原始宗教的萌生，也是人类从渔猎走向农业，母系社会转向父系社会的象征。元、明、清到民国民间则以烧制
民用生活用具为主。但在建筑用陶上则有很大发展，德州的官办砖窑则进贡到皇宫并做为长城用砖，窑址在今南郊窑上村始建于明
洪武三十年，在德州出土的砖有明代的官司印，如“大明成化十七年德州造”“大明成化十九年德州造”“大明正德十年德州造”等。', null, null, '德州市', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/德州黑陶-实景-01.jpg', null, null, '德州', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (20, '胡集书会', '胡集书会始于宋元、兴于明清，至今已有约800年历史，2006年被列入首批国家级非物质文化遗产名录，是中国北方现存最古老的民间曲艺交易集会之一。‌‌起源（宋元时期）‌：相传始于宋元，因胡集地处鲁北交通要道（近古黄河与大运河），商旅云集、民俗活跃，南北方说书艺人于每年正月十二大集自发汇聚“撂地卖艺、以书会友”，逐步形成年度惯例。‌发展与鼎盛（明清至清末民初）‌：明清时期随商品经济与运河商路繁荣，胡集成为鲁北重镇，“七十二店铺、钱庄十三家”，书会规模扩大，形成“前节（正月初一至十一）赶路、正节（正月十二至十六）卖场、偏节（十七至二十一）续雇”完整流程，西河大鼓、山东快书、琴书、评书等数十曲种齐聚，被誉为“一日看千台戏，三日读万卷书”。‌
‌近代起伏（1930s–1970s）‌：抗日战争后渐趋萧条；1950年代初短暂复兴（年均300档艺人）；1958年“大跃进”及三年困难时期再陷低谷；1961–1966年小幅回升；“文革”期间受冲击但未中断；1978年改革开放后随农村经济复苏再度繁荣。；胡集书会是兴起于山东省惠民县胡集镇的国家级非物质文化遗产，起源于宋元时期曲艺艺人的竞技活动，迄今已有800余年历史，后逐渐演变为以联谊为主的自发性民间曲艺交易活动，活动流程分为前节（新年至正月十二前）、正节（正月十二至十六）和偏节（正月十七至二十一）三个阶段。每年农历正月十二，全国曲艺艺人汇集此地展演，涵盖评书、西河大鼓、山东快书等65个曲种。
该活动于2006年列入首批国家级非物质文化遗产名录。1985年惠民县政府修建曲艺厅用于活动管理，2007年起实施“群众听书，政府买单”举措。2018年胡集镇获评“山东曲艺之乡”，2019年惠民县入选“中国曲艺之乡”。2023年惠民县文化馆重新被认定为项目保护单位。2025年书会开幕式发布专属标识及吉祥物“胡小艺”，活动增设全国美丽乡村曲艺展演等10项主题内容。', 117.7361190, 37.3316790, '惠民县胡集镇', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/胡集书会-实景-02.webp', null, null, '滨州', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (21, '曲阜孔庙', '始建于鲁哀公十七年（前478年），历代扩建；帝王祭孔，尊崇儒学', 117.0250000, 35.5960000, '曲阜孔庙大成殿', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/曲阜孔庙_实景_01.jpg', null, null, '曲阜', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (22, '曲阜阙里', '孔子故里，历代修建；帝王驾临祭孔，感怀先师', 117.0250000, 35.5960000, '阙里街', null, null, null, '曲阜', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (23, '文宣王庙（曲阜孔庙）', '始建于前478年，后王朝加封；写孔庙萧瑟景象，借古抒怀', 117.0250000, 35.5960000, '曲阜孔庙', null, null, null, '曲阜', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (24, '济宁太白楼', '始建于唐代，历代重修；追忆李白，赞颂其才名', 116.5880000, 35.4160000, '太白楼', null, null, null, '济宁', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (25, '济宁南池', '唐代已有，历代文人游赏；展现济宁的骚雅风流与自然之美', 116.5860000, 35.4120000, '南池公园', null, null, null, '济宁', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (26, '京杭大运河（济宁段）', '始建于春秋，元明清贯通；展现运河春日生机与活力', 116.5900000, 35.4100000, '京杭大运河沿岸', null, null, null, '济宁', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (27, '兖州城楼（遗址）', '兖州为古九州之一，城楼历代修缮；登楼远眺，感怀历史沧桑', 116.7870000, 35.5520000, '兖州老城', null, null, null, '济宁', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (28, '济宁石门山/泗水', '唐代已有游踪；以壮丽景色衬托离别之情', 117.0500000, 35.6000000, '石门山、泗水河', null, null, null, '济宁', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (29, '济宁浣笔泉', '传为李白洗笔处，清代重建；清幽景色，引发怀古之愁', 116.5840000, 35.4150000, '浣笔泉遗址', null, null, null, '济宁', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (30, '石佛寺（济宁）', '清代存，可能已圮；秋夜宁静，充满禅意', 116.5900000, 35.4080000, '石佛寺或相关区域', null, null, null, '济宁', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (31, '济宁王母阁（南城）', '始建于宋代，清代重建，已废；春日美景，城市与自然交融', 116.5880000, 35.4080000, '王母阁公园（原址）', null, null, null, '济宁', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (32, '峄山', '历史名山，秦始皇曾登临；描绘峄山奇特的洞穴与清泉', 116.9500000, 35.3500000, '峄山风景区', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/峄山_实景_01.jpg', null, null, '邹城', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (33, '济宁南湖', '古城南湖，历代游赏；春湖烟雨，意境朦胧', 116.5870000, 35.4070000, '南湖公园', null, null, null, '济宁', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (34, '东明漆园庄子钓台', '古漆园（庄子为吏处）一般认为在今陆圈镇裕州屯；庄寨为庄子归隐、著述、墓葬地
钓鱼台位于庄寨村北湿地，传为庄子垂钓处；漆园是庄子为官、悟道、著书之地，钓鱼台是他濮水垂钓、拒仕明志之所，共同承载道家逍遥哲学、天人合一思想与黄河隐逸文脉。', null, null, '山东省菏泽市东明县菜园集镇庄寨村', null, null, null, '菏泽', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (35, '东明县', '东明古称东昏，王莽始名东明，建制屡经兴废迁治，近现代先后隶属四省，1963 年正式划归山东菏泽至今。；东明底蕴厚重，是庄子故里、葵丘会盟之地，融合圣贤文化、春秋盟会文化与黄河民俗文化，兼具儒道历史底蕴与黄河地域特色。', null, null, '黄淮平原，位于山东省最西南部', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/东明县-实景-02.jpg.jpg', null, null, '菏泽', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (36, '东明漆园', '古漆园（庄子为吏处）一般认为在今陆圈镇裕州屯；庄寨为庄子归隐、著述、墓葬地
钓鱼台位于庄寨村北湿地，传为庄子垂钓处；漆园是庄子为官、悟道、著书之地，钓鱼台是他濮水垂钓、拒仕明志之所，共同承载道家逍遥哲学、天人合一思想与黄河隐逸文脉。', null, null, '山东省菏泽市东明县菜园集镇庄寨村', null, null, null, '菏泽', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (37, '东明', '东明古称东昏，王莽始名东明，建制屡经兴废迁治，近现代先后隶属四省，1963 年正式划归山东菏泽至今。；东明底蕴厚重，是庄子故里、葵丘会盟之地，融合圣贤文化、春秋盟会文化与黄河民俗文化，兼具儒道历史底蕴与黄河地域特色。', null, null, '黄淮平原，位于山东省最西南部', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/东明五霸岗-实景-03.jpg.jpg', null, null, '菏泽', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (38, '东明五霸岗', '古称葵丘，春秋时属宋国，地处宋、鲁、齐、晋四国交界，为诸侯会盟要地（前 651 年齐桓公葵丘会盟）；东明五霸岗即春秋葵丘会盟之地，是齐桓公确立霸业、尊王攘夷、诚信礼义的文化地标，承载春秋政治秩序、盟会礼仪与中原一统的历史精神', null, null, '山东省菏泽市东明县陆圈镇', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/东明五霸岗-实景-03.jpg.jpg', null, null, '菏泽', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (39, '郓城', '郓城始于春秋筑城、隋代定名，黄河孕育、千年建制，2600 年文脉不断，2019 年获评中国地名文化遗产 “千年古县”。；黄河厚土孕育 “水浒忠义、崇文尚武、戏曲非遗、黄河古脉” 四大文化，是好汉之乡、武术之乡、戏曲之乡、书画之乡。', null, null, '山东省西南部', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/郓城-实景-04.jpg.jpg', null, null, '菏泽', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (40, '郓州谿xi堂', '郓州谿堂（溪堂），唐长庆二年（822）由天平军节度使马总始建于古郓州（今东平县老湖镇须昌故城）官署西北隅，引汶水活水成溪，故名 “谿堂”。；它是唐代德政象征、北方官署园林典范，因韩愈名篇名扬后世，成为汶水流域历代文人雅集的精神地标，融理政思想、文学文脉、园林美学、人文情怀于一体。', null, null, '东平县老湖镇政府西南，古须昌城遗址范围内，距东平县城约 20 公里，距郓城县西南边境约 30 公里。', null, null, null, '菏泽', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (41, '郓州', '郓城始于春秋筑城、隋代定名，黄河孕育、千年建制，2600 年文脉不断，2019 年获评中国地名文化遗产 “千年古县”。；黄河厚土孕育 “水浒忠义、崇文尚武、戏曲非遗、黄河古脉” 四大文化，是好汉之乡、武术之乡、戏曲之乡、书画之乡。', null, null, '山东省西南部', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/郓州谿堂-实景-05.jpg.webp', null, null, '菏泽', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (42, '新堂', '郓州谿堂（溪堂），唐长庆二年（822）由天平军节度使马总始建于古郓州（今东平县老湖镇须昌故城）官署西北隅，引汶水活水成溪，故名 “谿堂”。；它是唐代德政象征、北方官署园林典范，因韩愈名篇名扬后世，成为汶水流域历代文人雅集的精神地标，融理政思想、文学文脉、园林美学、人文情怀于一体。', null, null, '东平县老湖镇政府西南，古须昌城遗址范围内，距东平县城约 20 公里，距郓城县西南边境约 30 公里。', null, null, null, '泰安', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (43, '郓城七陵碑古迹', '七陵碑为汉代遗存，因碑得名村落，明清跻身郓城名胜，原碑后世损毁，仅留遗址与相关史载传承至今。；它是鲁西南珍贵汉代篆书石刻，兼具书法考古价值，因 “七陵” 存历史谜团，依托林木烟云景致成为当地标志性人文景观与乡土文化符号。', null, null, '山东省菏泽市郓城县郭屯镇七陵碑村', null, null, null, '菏泽', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (44, '濮州', '隋唐至明清的古州，核心在今鲁西南鄄城、豫东北范县一带，州治先在山东鄄城，后迁河南范县濮城镇，地跨黄河两岸，扼濮水 / 黄河要冲。；古濮水文明核心、黄河下游水陆枢纽，承载颛顼遗墟、昆吾旧壤、卫郑齐鲁交汇的历史层积，也是黄河水患与治河史的典型见证。', null, null, '山东省西南部、菏泽市北部', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/濮州-实景-07.jpg.jpg', null, null, '菏泽', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (45, '古鄄城', '古鄄城自先秦便是城邑，秦汉置县，隋唐至明初长期为濮州治所，后因黄河水患州治外迁，故城改称旧城，历经千年建制更迭延续至今。；尧舜文化发祥地、孙膑故里与曹魏建安文化重要传承地，地处黄河沿岸，融合上古圣迹、兵家智慧、名士文脉与黄河民俗，底蕴厚重。', null, null, '山东省菏泽市鄄城县旧城镇（旧城集）', null, null, null, '菏泽', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (46, '濮水', '先秦至汉魏水系兴盛、水陆通达，后世受黄河淤积、改道影响逐步断流湮没。；上古濮文化发源地，因 “桑间濮上” 闻名，见证诸多历史事件，是兼具典故价值与地域风情的文化古水。', null, null, '地处冀鲁豫三省交界的黄河冲积平原，紧邻古濮州、古鄄城、濮阳城，是区域内古代重要水系，如今主干河道早已淤塞消失，仅留存濮城、濮水等地名、古堤与遗迹。', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/濮水-实景-09.jpg.jpg', null, null, '菏泽', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (47, '曹植读书台', '三国时期曹植受封鄄城王时修筑，后因黄河淤积渐遭埋没，现存遗址。；它是建安文学的重要遗存，见证曹植诗文创作，承载着建安风骨与千年文人文脉。', null, null, '山东省菏泽市鄄城县旧城镇杏花岗村西南（古鄄城旧城东北约 1 公里）', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/曹植读书台-实景-10.jpg.jpg', null, null, '菏泽', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (48, '古会台', '春秋筑台用于诸侯会盟，后世屡遭黄河水患损毁，现存多层古文化堆积遗址。；因葵丘之盟闻名，是春秋霸政的标志性遗存，也是古代信义与礼乐文化的实物见证。', null, null, '山东省菏泽市鄄城县旧城镇葵堌堆村西（村北）', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/葵丘古会台-实景-11.jpg.jpg', null, null, '菏泽', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (49, '鄄城', '古鄄城自先秦便是城邑，秦汉置县，隋唐至明初长期为濮州治所，后因黄河水患州治外迁，故城改称旧城，历经千年建制更迭延续至今。；尧舜文化发祥地、孙膑故里与曹魏建安文化重要传承地，地处黄河沿岸，融合上古圣迹、兵家智慧、名士文脉与黄河民俗，底蕴厚重。', null, null, '山东省菏泽市鄄城县旧城镇（旧城集）', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/鄄城-实景-08.jpg.png', null, null, '菏泽', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (50, '楚丘城', '上古为楚人先祖聚居地，商汤曾在此会盟，后世历经变迁，如今保留有堌堆遗迹。；既是楚人早期发祥之地，也是商汤会盟之所，融汇了上古部族文明与早期王朝礼制文化。', null, null, '山东省菏泽市曹县东北侯集镇梁堌堆村（景山遗址）', null, null, null, '菏泽', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (51, '古濮水', '先秦至汉魏水系兴盛、水陆通达，后世受黄河淤积、改道影响逐步断流湮没。；上古濮文化发源地，因 “桑间濮上” 闻名，见证诸多历史事件，是兼具典故价值与地域风情的文化古水。', null, null, '地处冀鲁豫三省交界的黄河冲积平原，紧邻古濮州、古鄄城、濮阳城，是区域内古代重要水系，如今主干河道早已淤塞消失，仅留存濮城、濮水等地名、古堤与遗迹。', null, null, null, '菏泽', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (52, '曹州城', '北周始设曹州，金代迁至今址，明清升为府治，建制历经更迭，古城脉络延续至今。；此地为上古文明沃土，兼具牡丹文化、水浒忠义文化与黄河民俗风情，文化底蕴深厚多元。', null, null, '山东菏泽市牡丹区老城区', null, null, null, '菏泽', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (53, '凝香园', '始建于明代，历经修缮与更迭，是鲁西南现存历史悠久的古典园林。；以花木景致与古典造园艺术见长，承载当地园林文化与人文雅韵。', null, null, '山东省菏泽市鲁西新区岳程办事处岳楼行政村', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/凝香园-实景-14.jpg.jpg', null, null, '菏泽', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (54, '曹州牡丹', '北周始设曹州，金代迁至今址，明清升为府治，建制历经更迭，古城脉络延续至今。；此地为上古文明沃土，兼具牡丹文化、水浒忠义文化与黄河民俗风情，文化底蕴深厚多元。', null, null, '山东菏泽市牡丹区老城区', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/曹州牡丹-实景-15.jpg.jpg', null, null, '菏泽', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (55, '东阿', '曹魏时期曹植受封东阿王，在此居处理政、著文度日，封地建制后世几经沿革。；曹植居东阿期间留下诸多诗文与遗迹，是三国文学、建安文化在鲁西地区的重要载体。', null, null, '山东省聊城市东阿县', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/东阿-实景-16.jpg.jpg', null, null, '聊城', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (56, '阿胶', '阿胶起源于先秦，汉代始载典籍，唐代定型为驴皮熬制，历代作为贡品传承至今，其传统制作技艺现已列入国家级非物质文化遗产。；它是鲁西地域特色物产与传统中医药文化的代表，因历代名人推崇、宫廷御用加持，兼具养生价值与深厚的人文底蕴。', null, null, '山东省聊城市东阿县', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/阿胶-实景-17.jpg.jpg', null, null, '聊城', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (57, '高唐', '高唐有2800 余年文字史，春秋为齐国高唐邑，西汉初正式置县，北齐天保七年迁今址，宋元明清升为高唐州，民国复改为县，沿用至今，自古为鲁西重镇，素有 “金高唐” 之称。；高唐是黄河文化、农耕商贸文化、书画艺术文化、水浒民俗文化交融之地，以“书画之乡、锦鲤之都、金高唐”为核心文化标识。', null, null, '山东聊城高唐县', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/高唐-实景-18.jpg.jpg', null, null, '聊城', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (58, '东阿县', '春秋称柯、战国为阿，秦置东阿县，曹植封王、阿胶贡御，千年古县，黄河阿胶文化核心地；东阿坐拥黄河文化底蕴，以阿胶养生文化、鱼山梵呗佛教音乐文化为两大核心，兼有名士文脉与吉祥民俗，地域文化特色鲜明。', null, null, '山东省西部，聊城市东南部，泰山脚下，黄河岸边', null, null, null, '聊城', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (59, '阳谷县', '春秋为阳谷邑，隋代正式置县，建制历经沿革，近现代几经撤并后恢复，县名与地域传承至今。；阳谷是黄河文化、运河文化、水浒文化交融地，底蕴深厚', null, null, '山东省聊城市阳谷县', null, null, null, '聊城', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (60, '盟台', '始建于春秋时期，是齐桓公召集诸侯会盟所筑高台，为阳谷历史古迹，后世留存遗址至今。；见证春秋诸侯会盟、尊王攘夷的历史，是齐鲁盟会文化与早期霸业文明的实物遗存，位列阳谷古八景。', null, null, '阳谷县城西南隅', null, null, null, '聊城', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (61, '灵泉', '灵泉（古阿井）自古闻名，汉魏起便用于熬制阿胶，历代屡经修缮保护，留存至今。；它是阿胶文化的发源地，依托优质泉水成就传统制胶技艺，融合医药、运河与人文传说，底蕴深厚。', null, null, '山东省聊城市阳谷县阿城镇西北、古运河西岸、东阿故城遗址内', null, null, null, '聊城', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (62, '黄河古渡', '该古渡自明代起即为鲁中淄川、博山往返河北直隶的必经跨黄渡口，是淄博北部最重要的黄河水陆转运节点。清代常年停靠客船、货船，春夏汛期风浪汹涌，秋冬枯水期通航繁忙，无数文人、商旅、官吏由此渡河，沿用数百年，是齐地黄河沿线标志性古渡口。；作为淄博本土文学家，蒲松龄以第一视角实录黄河渡河全过程，细致刻画巨浪、狂风、小舟颠簸的惊险旅途。诗作跳出单纯写景，既留存了清代高青段黄河真实水文特征，又记录清代齐地跨黄行旅风貌；同时以个人羁旅视角，将黄河雄浑自然气势与游子旅途心境相融，兼具水利史料价值、旅行文学价值与齐地地域文学特色。', 118.0426000, 37.1752000, '高青县北部黄河干流古渡口', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/黄河古渡_实景_01.jpg.jpg', null, null, '淄博', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (63, '马踏湖', '锦秋湖即马踏湖，依托黄河古河道洼地形成，依靠黄河支渠引水充盈湖面，湖区盛产莼菜、水产，自古为齐北著名水乡，盛产湖鲜，是本地百姓渔耕赖以生存的水域；王士禛立足家乡湖景创作竹枝词，将淄博黄河水系孕育的锦秋湖与江南名湖对比，夸赞本地湖景与湖鲜物产，凸显黄河滋养下齐地水乡独有的风物魅力，承载齐地本土水乡文化自信', 118.0869000, 37.1151000, '桓台县起凤镇马踏湖（古名锦秋湖）', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/马踏湖_实景_01.jpg.jpg', null, null, '淄博', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (64, '东津渡', '东津渡坐落利津城东黄河岸，为明清黄河三角洲核心水陆码头，连通京津与胶东，商旅、学子、渔舟往来不绝，位列利津古八景之首，素有黄河 “小天津” 之称；依托黄河干流航运发展商贸，是古代鲁北跨河交通枢纽。；明成化利津儒学训导章忠本地实景创作，完整描摹拂晓时分黄河渡口繁忙图景，记录黄河干流航运商贸盛景；既绘黄河长河、晨雾浪涛、竞渡舟楫的自然河景，又写舟子、行旅、渔人的人间烟火，末句借渡口安宁景象称颂当朝治世，兼具黄河地理纪实与地方民生人文价值。', 118.2842000, 37.4916000, '利津县利津街道城东黄河沿岸东津古渡旧址', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/东津渡_实景_01.jpg.jpeg', null, null, '东营', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (65, '黄河大堤', '清代为管控黄河水患，沿大清河两岸修筑连绵防洪大堤，堤岸遍植垂柳；安澜场是利津独有的黄河护堤管理设施，周边配套田庄、渔埠，农、渔、河工在此聚居，傍晚时分渔船归港，是当地民众休闲游赏的河岸胜地。；利津本土诗人漫步黄河大堤，于黄昏眺望河堤、河场、归帆，将黄河水利设施、沿岸农耕渔业景象与文人宴游结合。诗歌以本地独有水利地名 “安澜场” 为核心意象，既写实记录东营清代黄河堤防治理成果，又描绘黄河岸边悠然的市井渔耕生活，承载黄河水利文化与三角洲乡土风情。', 118.2796000, 37.4895000, '利津县城近郊大清河南岸黄河大堤、安澜场一带', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/黄河大堤_实景_01.jpg.jpg', null, null, '东营', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (66, '泰山·岱顶观河', '泰山为历代封禅圣地，登岱观河自唐代始成文学母题。；以黄河为飘带反衬泰山之崇高，体现“登高望远”的精神境界。', null, null, '泰山玉皇顶、日观峰等山顶区域', null, null, null, '泰安', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (67, '大明湖·小沧浪亭', '清代阮元建亭，取“沧浪之水”意命名。；阮元“黄河如带”成为济南望河的经典意象。', null, null, '大明湖南岸，历下亭西侧', null, null, null, '济南', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (68, '济南·趵突泉', '趵突泉有“天下第一泉”之称，明清文人多咏。；以“王屋伏流”传说暗指黄河源头，将泉与黄河精神相连。', null, null, '济南市历下区趵突泉南路1号', null, null, null, '济南', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (69, '济宁·太白酒楼', '唐代贺兰氏酒楼，李白常饮于此，后世建楼纪念。；“饮啖黄河鱼”将黄河风物与李白诗酒精神融合。', null, null, '济宁市任城区古运河北岸', null, null, null, '济宁', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
INSERT INTO sjg.scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, video_url, region, created_at, updated_at) VALUES (70, '青岛·崂山', '崂山为道教名山，李白曾游并留诗。；李白游崂山是其齐鲁文化体验的一部分，诗中以飞升意象寄托仙道情怀。', null, null, '青岛市崂山区', null, null, null, '青岛', '2026-06-17 18:00:50', '2026-06-17 18:00:50');
