USE sjg;

-- Clean existing test data first to prevent duplicate errors if run multiple times
DELETE FROM poem_event;
DELETE FROM poem;
DELETE FROM event;
DELETE FROM poet;
DELETE FROM scenic_spot;

-- 1. Scenic Spots
INSERT INTO scenic_spot (id, name, description, longitude, latitude, address, image_url, image_anime_url, region) VALUES
(1, '瓒电獊娉?, '瓒电獊娉変綅鍒楁祹鍗椻€滀竷鍗佷簩鍚嶆硥鈥濅箣棣栵紝琚獕涓衡€滃ぉ涓嬬涓€娉夆€濄€傛硥姘存竻婢堣搴曪紝涓夎偂娉夋按鍠锋秾鑰屽嚭锛屾樇澶滀笉鍋滐紝鏄祹鍗楁硥姘存枃鍖栫殑鏍囧織銆?, 117.0156000, 36.6618000, '灞变笢鐪佹祹鍗楀競鍘嗕笅鍖鸿兜绐佹硥鍗楄矾1鍙?, 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/baotu_spring.jpg', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/baotu_spring_anime.jpg', '娴庡崡'),
(2, '澶ф槑婀?, '澶ф槑婀栨槸鐢辨祹鍗椾紬澶氭硥姘存眹娴佽€屾垚鐨勫ぉ鐒舵箹娉婏紝婀栭潰瀹介様锛岃嵎鑺辨弧濉樸€傚彜鏈夆€滃洓闈㈣嵎鑺变笁闈㈡煶锛屼竴鍩庡北鑹插崐鍩庢箹鈥濈殑缇庤獕锛屾槸鍘嗕唬鏂囦汉闆呰仛鐨勬牳蹇冨満鎵€銆?, 117.0256000, 36.6733000, '灞变笢鐪佹祹鍗楀競鍘嗕笅鍖哄ぇ鏄庢箹璺?71鍙?, 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/daming_lake.jpg', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/daming_lake_anime.jpg', '娴庡崡'),
(3, '娉板北', '娉板北涓轰簲宀充箣棣栵紝鑷彜琚涓哄浗瀹舵槍鐩涖€佹皯鏃忓洟缁撶殑璞″緛銆傚北鍔块泟浼熷．涓斤紝鍘嗕唬甯濈帇鍦ㄦ灏佺锛屾枃浜洪獨瀹㈠湪姝ょ暀涓嬩簡鏁颁互鍗冭鐨勭鍒讳笌璇楁瓕銆?, 117.1043000, 36.2562000, '灞变笢鐪佹嘲瀹夊競娉板北鍖虹孩闂ㄨ矾', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/mount_tai.jpg', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/mount_tai_anime.jpg', '娉板畨'),
(4, '鏇查槣涓夊瓟', '鏇查槣鐨勫瓟搴欍€佸瓟搴溿€佸瓟鏋楀悎绉扳€滀笁瀛斺€濓紝鏄邯蹇典笌绁瀛斿瓙鐨勫湥鍦帮紝涔熸槸鍎掑鏂囧寲鐨勬牳蹇冭浇浣撱€傚叾鍙ゅ缓绛戠兢瀹忎紵澹附锛岀鍒绘灄绔嬶紝鏂囧寲搴曡暣鏋佸叾娣卞帤銆?, 116.9897000, 35.5910000, '灞变笢鐪佹洸闃滃競绁為亾琛?, 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/three_confucius.jpg', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/three_confucius_anime.jpg', '娴庡畞'),
(5, '榛勬渤鍏ユ捣鍙?, '榛勬渤鍦ㄨ繖閲屾眹鍏ユ袱娴凤紝鍛堢幇鍑衡€滈粍钃濅氦姹団€濈殑鑷劧濂囪銆傝繖閲屾嫢鏈変笘鐣屼笂鏈€瀹屾暣銆佹渶骞磋交鐨勬箍鍦扮敓鎬佺郴缁燂紝鏄劅鍙椻€滈粍娌充箣姘村ぉ涓婃潵锛屽娴佸埌娴蜂笉澶嶈繕鈥濇渶缁堝綊瀹跨殑缁濅匠鍦扮偣銆?, 119.1600000, 37.7500000, '灞变笢鐪佷笢钀ュ競鍨﹀埄鍖洪粍娌充笁瑙掓床鍥藉绾ц嚜鐒朵繚鎶ゅ尯', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/yellow_river_estuary.jpg', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/yellow_river_estuary_anime.jpg', '涓滆惀'),
(6, '鍏夊渤妤?, '鍏夊渤妤兼槸鍥藉鍘嗗彶鏂囧寲鍚嶅煄鑱婂煄鐨勮薄寰侊紝寤轰簬鏄庝唬娲骞撮棿锛屾槸涓€搴ч泟浼熺殑鏈ㄦ瀯妤奸榿銆傚畠鍦板涓滄槍鍙ゅ煄涓ぎ锛屽彲淇灠鏁翠釜鍙ゅ煄涓庝笢鏄屾箹椋庡厜銆?, 115.9863000, 36.4526000, '灞变笢鐪佽亰鍩庡競涓滄槍搴滃尯鍙ゅ煄涓ぎ', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/guangyue_tower.jpg', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/guangyue_tower_anime.jpg', '鑱婂煄'),
(7, '钂叉澗榫勭邯蹇甸', '浣嶄簬娣勫崥甯傛穭宸濆尯钂插搴勶紝渚濇墭钂叉澗榫勬晠灞呰€屽缓銆傞鍐呮湁钁楀悕鐨勨€滄煶娉夆€濓紝鏄挷鏉鹃緞褰撳勾璁捐尪閲囬銆佸垱浣溿€婅亰鏂嬪織寮傘€嬬殑鍘熷潃銆?, 118.0125000, 36.6540000, '灞变笢鐪佹穭鍗氬競娣勫窛鍖鸿挷瀹跺簞', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/pu_manor.jpg', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/pu_manor_anime.jpg', '娣勫崥'),
(8, '鑻忕鐜嬪', '鍧愯惤浜庡痉宸炲競鍖楅儴锛屾槸瀹夎懍鏄庝唬鏉ュ崕璁块棶鐨勫彜鑻忕鍥斤紙浠婅彶寰嬪锛変笢鐜嬪反閮借憶鍙瓟鍓岀殑闄靛锛岃璇佷簡娴蜂笂涓濈桓涔嬭矾涓庝腑澶栧弸濂藉線鏉ョ殑杈夌厡鍘嗗彶銆?, 116.3056000, 37.4721000, '灞变笢鐪佸痉宸炲競寰峰煄鍖?, 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/sulu_tomb.jpg', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/sulu_tomb_anime.jpg', '寰峰窞'),
(9, '榄忔皬搴勫洯', '浣嶄簬婊ㄥ窞甯傛儬姘戝幙锛屾槸娓呬唬甯冨眬鐙壒鐨勫煄鍫″紡姘戝眳寤虹瓚缇ゃ€傚簞鍥瀺鍚堜簡鍖椾含鍥涘悎闄笌鍐涗簨闃插尽鍫″瀿鐨勮璁★紝鏄粍娌充笅娓搁瞾鍖楀钩鍘熶笂涓€棰楃拃鐠ㄧ殑姘戝眳鏄庣彔銆?, 117.5256000, 37.3733000, '灞变笢鐪佹花宸炲競鎯犳皯鍘块瓘闆嗛晣', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/wei_manor.jpg', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/wei_manor_anime.jpg', '婊ㄥ窞'),
(10, '鏇瑰窞鐗′腹鍥?, '浣嶄簬鑿忔辰甯傜墶涓瑰尯锛屾槸涓栫晫涓婇潰绉渶澶с€佸搧绉嶆渶澶氱殑鐗′腹涓婚鍏洯銆傝弿娉藉彜绉版浌宸烇紝浠ョ墶涓圭敳澶╀笅锛屽巻浠ｆ枃浜哄ⅷ瀹㈠湪姝ょ暀涓嬩簡鏃犳暟璧忚姳璧炶姳鐨勮瘲浣溿€?, 115.4856000, 35.2633000, '灞变笢鐪佽弿娉藉競鐗′腹鍖轰汉姘戣矾', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/peony_garden.jpg', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/spots/peony_garden_anime.jpg', '鑿忔辰');

-- 2. Poets
INSERT INTO poet (id, name, dynasty_id, birth_year, death_year, birthplace, biography, avatar_url, avatar_anime_url, style) VALUES
(1, '鏉庣櫧', 4, 701, 762, '闄囪タ鎴愮邯锛堜粖鐢樿們绉﹀畨锛?, '瀛楀お鐧斤紝鍙烽潚鑾插眳澹紝鍞愪唬浼熷ぇ鐨勬氮婕富涔夎瘲浜猴紝琚悗浜鸿獕涓衡€滆瘲浠欌€濄€備粬鏇惧娆℃父鍘嗗北涓滐紙榻愰瞾澶у湴锛夛紝骞跺湪娴庡崡銆佹嘲灞便€佷换鍩庯紙浠婃祹瀹侊級绛夊湴鐣欎笅浜嗗ぇ閲忚剭鐐欎汉鍙ｇ殑璇楃瘒锛屼笌鏉滅敨鍦ㄩ綈椴佺浉浼氭洿鏄腑鍥芥枃瀛﹀彶涓婄殑涓€娈典匠璇濄€?, 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/poets/li_bai.jpg', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/poets/li_bai_anime.jpg', '娴极涓讳箟銆佽豹鏀鹃閫搞€侀泟濂囧鏀?),
(2, '鏉滅敨', 4, 712, 770, '娌冲崡宸╁幙锛堜粖娌冲崡宸╀箟锛?, '瀛楀瓙缇庯紝鑷彿灏戦櫟閲庤€侊紝鍞愪唬浼熷ぇ鐨勭幇瀹炰富涔夎瘲浜猴紝琚笘浜哄皧涓衡€滆瘲鍦ｂ€濓紝鍏惰瘲琚О涓衡€滆瘲鍙测€濄€傞潚骞存椂鏈熸浘娓稿巻榻愰瞾锛屽啓涓嬩簡姘斿悶灞辨渤鐨勩€婃湜宀炽€嬨€傚湪鍘嗕笅锛堜粖娴庡崡锛夊ぇ鏄庢箹鐣斾笌楂橀€傘€佹潕閭曠瓑浜鸿仛浼氾紝鐣欎笅浜嗏€滄捣鍙虫浜彜锛屾祹鍗楀悕澹鈥濈殑鍗冨彜鍚嶅彞銆?, 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/poets/du_fu.jpg', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/poets/du_fu_anime.jpg', '鐜板疄涓讳箟銆佹矇閮侀】鎸€佸咖鍥藉咖姘?),
(3, '鏉庢竻鐓?, 5, 1084, 1155, '榻愬窞绔犱笜锛堜粖灞变笢娴庡崡绔犱笜锛?, '鍙锋槗瀹夊眳澹紝瀹嬩唬濂宠瘝浜猴紝濠夌害璇嶆淳浠ｈ〃锛屾湁鈥滃崈鍙ょ涓€鎵嶅コ鈥濅箣绉般€傚ス鍑虹敓浜庢祹鍗楋紝闈掑勾鏃舵湡鍦ㄦ祹鍗楀害杩囦簡鏃犲咖鏃犺檻鐨勭編濂芥椂鍏夛紝鍏惰瘝浣滃鍐欐邯浜棩鏆€佽棔鑺辨繁澶勭瓑娴庡崡椋庡厜锛屽叾娓呬附鍏搁泤鐨勯鏍兼垚涓烘祹鍗楁枃瀛︽櫙瑙傜殑閲嶈搴曡壊銆?, 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/poets/li_qingzhao.jpg', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/poets/li_qingzhao_anime.jpg', '濠夌害娓呬附銆佹儏娣辨剰鍒囥€佺粏鑵诲濠?),
(4, '杈涘純鐤?, 5, 1140, 1207, '鍘嗗煄锛堜粖灞变笢娴庡崡锛?, '瀛楀辜瀹夛紝鍙风杞╋紝鍗楀畫璞斁娲捐瘝浜恒€佸皢棰嗭紝涓庤嫃杞煎悎绉扳€滆嫃杈涒€濓紝涓庢潕娓呯収骞剁О鈥滄祹鍗椾簩瀹夆€濄€備粬鍑虹敓浜庨噾鍥芥拨闄峰尯锛岄潚骞存椂鏈熷湪灞变笢鑱氫紬璧蜂箟鎶曞鍗楀畫銆傚叾璇嶄綔鎱锋叏婵€鏄傦紝鍏呮弧鏀跺澶卞湴鐨勬弧鑵旂儹琛€鍜屾姤鍥芥棤闂ㄧ殑澹織闅鹃叕銆?, 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/poets/xin_qiji.jpg', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/poets/xin_qiji_anime.jpg', '璞斁闆勫．銆佹叿鎱ㄦ偛鍑夈€佹皵鍔跨绀?),
(5, '璧靛瓱闋?, 6, 1254, 1322, '鍚村叴锛堜粖娴欐睙婀栧窞锛?, '瀛楀瓙鏄傦紝鍙锋澗闆亾浜猴紝鍏冧唬钁楀悕鐢诲銆佷功娉曞銆佽瘲浜恒€傛浘浠诲悓鐭ユ祹鍗楄矾鎬荤搴滀簨锛屽湪娴庡崡浠昏亴鏈熼棿锛屼粬娣辨繁琚祹鍗楃殑灞辨按椋庡厜鎵€鍚稿紩锛屽垱浣滀簡澶ч噺鎻忕粯娴庡崡灞辨按鐨勪功鐢讳笌璇楁瓕锛屽叾涓互銆婇箠鍗庣鑹插浘銆嬪拰銆婅兜绐佹硥銆嬭瘲鏈€涓鸿憲鍚嶃€?, 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/poets/zhao_mengfu.jpg', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/poets/zhao_mengfu_anime.jpg', '娓呬附鍏搁泤銆佹剰澧冩繁杩溿€佹枃璐ㄥ浆褰?),
(6, '钂叉澗榫?, 8, 1640, 1715, '灞变笢娣勫窛锛堜粖娣勫崥甯傛穭宸濆尯锛?, '瀛楃暀浠欙紝涓€瀛楀墤鑷ｏ紝鍒彿鏌虫硥灞呭＋锛屼笘绉拌亰鏂嬪厛鐢燂紝娓呬唬鏉板嚭鐨勫皬璇村銆佽瘲浜恒€備粬鍦ㄥ涔℃穭鍗氭挵鍐欎簡鍚嶆壃涓栫晫鐨勬枃瑷€鐭瘒灏忚闆嗐€婅亰鏂嬪織寮傘€嬨€傝挷鏉鹃緞涓€鐢熷鍦ㄥ涔″強鍛ㄨ竟娓稿巻璁插锛屽叾璇楁枃璇嶆洸涔熸瀬鍏烽綈椴佸湴鏂规枃鍖栫壒鑹层€?, 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/poets/pu_songling.jpg', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/poets/pu_songling_anime.jpg', '骞芥矇濂囧够銆侀€氫織鐢熷姩銆佸啓瀹炰笌娴极缁撳悎');

-- 3. Poems
INSERT INTO poem (id, title, content, poet_id, dynasty_id, spot_id, annotation, background, audio_url, video_url, sentiment_tags) VALUES
(1, '鏈涘渤', '宀卞畻澶浣曪紵榻愰瞾闈掓湭浜嗐€俓n閫犲寲閽熺绉€锛岄槾闃冲壊鏄忔檽銆俓n鑽¤兏鐢熸浘浜戯紝鍐崇湨鍏ュ綊楦熴€俓n浼氬綋鍑岀粷椤讹紝涓€瑙堜紬灞卞皬銆?, 2, 4, 3, '銆愬脖瀹椼€戞嘲灞变害鍚嶅脖灞憋紝涓轰簲宀充箣棣栵紝鏁呭皧涓哄脖瀹椼€俓n銆愰綈椴侀潚鏈簡銆戝攼浠ｉ綈椴佷袱鍥戒互娉板北涓虹晫锛岄潚鏈簡鎸囨嘲灞辩坏寤朵笉缁濓紝闈掔繝涔嬭壊涓嶅敖銆俓n銆愰€犲寲銆戞寚澶ц嚜鐒躲€俓n銆愰挓銆戣仛闆嗐€俓n銆愬壊銆戝垝鍒嗐€俓n銆愬喅鐪︺€戠湨锛岀溂瑙掋€傚喅锛岃寮€銆傚舰瀹规瀬鍔涘紶澶х溂鐫涚湅銆俓n銆愪細褰撱€戠粓褰擄紝蹇呭畾銆?, '杩欓璇楁槸鏉滅敨寮€鍏冧簩鍗佸洓骞达紙736骞达級娓稿巻榻愰瞾鏃舵墍鍐欍€傚綋鏃惰瘲浜轰簩鍗佸洓宀侊紝姝ｅ€奸鍗庢鑼傦紝绉戜妇鑰冭瘯钀界鍚庢极娓稿惔瓒娿€侀綈椴併€傞潰瀵归泟浼熷．涓界殑娉板北锛岃瘲浜烘弧鎬€璞儏锛屽啓涓嬩簡杩欓姘旇薄涓囧崈銆佷紶璇靛崈鍙ょ殑鏉颁綔锛屽睍鐜颁簡骞磋交鏉滅敨鏄傛壃鍚戜笂銆佸織瀛橀珮杩滅殑鍗氬ぇ鑳告€€銆?, 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/audio/wang_yue.mp3', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/video/wang_yue.mp4', '["璞斁", "闆勫", "澹織"]'),
(2, '闄潕鍖楁捣瀹村巻涓嬩涵', '涓滆棭椹荤殏鐩栵紝鍖楁捣闃佹竻灏娿€俓n椋庡箷鍙屾祦鎬ワ紝娌欏洯涓囦簳鍒嗐€俓n娴峰彸姝や涵鍙わ紝娴庡崡鍚嶅＋澶氥€俓n浜戝北宸插彂鍏达紝鐜変僵浼嫑榄傘€俓n鏂愬洖浣滆涔愶紝浣嗘瓕瀹翠綑娓┿€?, 2, 4, 2, '銆愭潕鍖楁捣銆戝嵆鏉庨倳锛屾浘浠诲寳娴峰お瀹堬紝褰撴椂鍚嶅櫔涓€鏃剁殑鏂囧瀹跺拰涔︽硶瀹躲€俓n銆愬巻涓嬩涵銆戜綅浜庢祹鍗楀ぇ鏄庢箹鐣斻€俓n銆愭捣鍙炽€戝彜浜轰互涓滀负鍙筹紝娴峰彸鎸囧北涓滄垨娴庡崡涓€甯︺€俓n銆愪极銆戠瓑寰呫€?, '澶╁疂鍥涘勾锛?45骞达級澶忥紝鏉滅敨鍦ㄩ綈椴佹极娓告湡闂达紝涓庢潕鍖楁捣锛堟潕閭曪級銆侀珮閫傜瓑浜哄悓瀹翠簬娴庡崡澶ф槑婀栫殑鍘嗕笅浜€傚腑闂存潨鐢湁鎰熶簬鍘嗕笅鍚嶅＋涔嬪涓庡彜浜箣骞斤紝鍐欎笅浜嗚繖棣栧闆嗚瘲锛屽叾涓€滄捣鍙虫浜彜锛屾祹鍗楀悕澹鈥濇垚涓轰簡娴庡崡鏈€鍏蜂唬琛ㄦ€х殑鍩庡競鏂囧寲鍚嶇墖銆?, 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/audio/lishi_ting.mp3', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/video/lishi_ting.mp4', '["闆呰嚧", "瀹翠箰", "鎬€鍙?]'),
(3, '濡傛ⅵ浠ぢ峰父璁版邯浜棩鏆?, '甯歌婧涵鏃ユ毊锛屾矇閱変笉鐭ュ綊璺€俓n鍏村敖鏅氬洖鑸燂紝璇叆钘曡姳娣卞銆俓n浜夋浮锛屼簤娓★紝鎯婅捣涓€婊╅弗楣€?, 3, 5, 2, '銆愭邯浜€戞祹鍗楀悕鑳溿€傚畫浠ｅ缓鏈夋邯浜紝涓磋繎娉夋按銆俓n銆愭矇閱夈€戝ぇ閱夈€俓n銆愪簤娓°€戜簤鐫€鍒掕埞杩囨浮銆俓n銆愰弗楣€戞按楦熷悕銆?, '杩欓璇嶆槸鏉庢竻鐓ф棭鏈熺殑浠ｈ〃浣滐紝鍐欎簬濂瑰嚭瀚佸墠灞呬綇鍦ㄦ祹鍗楃殑灏戝コ鏃舵湡銆傝瘝涓敓鍔ㄥ湴鍥炲繂浜嗘煇娆″湪澶ф槑婀栫晹鎴栭儕澶栨邯娴佷腑鍒掕埞娓哥帺锛屽洜楗厭澶ч唹鑰岃糠璺紝璇叆鑽疯姳涓涗腑锛屾儕椋炴按楦熺殑娆箰鍦烘櫙锛屽厖婊℃椿娉肩殑闈掓槬姘旀伅锛屾瀬鍏风敓娲绘儏瓒ｃ€?, 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/audio/rumengling.mp3', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/video/rumengling.mp4', '["濠夌害", "鎭贰", "娆㈡剦"]'),
(4, '瓒电獊娉?, '娉烘按鍙戞簮澶╀笅鏃狅紝骞冲湴娑屽嚭鐧界帀澹躲€俓n璋疯櫄涔呮亹鍏冩皵娉勶紝宀佹棻涓嶆剚涓滄捣鏋€俓n浜戦浘娑﹁捀鍗庝笉娉紝娉㈡緶澹伴渿澶ф槑婀栥€俓n鏃舵潵娉変笂婵皹鍦燂紝鍐伴洩婊℃€€娓呭叴瀛ゃ€?, 5, 6, 1, '銆愭澈锛坙u貌锛夋按銆戞寚瓒电獊娉夌殑娉夋按锛屽彜绉版澈姘淬€俓n銆愮櫧鐜夊６銆戝舰瀹规硥姘存磥鐧芥櫠鑾癸紝浠庡钩鍦版秾鍑猴紝濡傚悓鐧界帀闆曟垚鐨勫６銆俓n銆愬崕涓嶆敞銆戝北鍚嶏紝鍗冲崕灞憋紝浣嶄簬娴庡崡甯備笢鍖楅儴銆俓n銆愬ぇ鏄庢箹銆戞祹鍗楀悕鑳滐紝瓒电獊娉夋按姹囧叆澶ф槑婀栥€俓n銆愭刊锛坺hu贸锛夈€戞礂娑ゃ€?, '杩欓璇楁槸鍏冧唬钁楀悕涔︾敾瀹惰档瀛熼牜浠昏亴娴庡崡鏈熼棿鍒涗綔鐨勩€備粬鍦ㄦ硥鐣旀父鐜╋紝琚兜绐佹硥骞冲湴娉夋按鍠锋秾濡傜櫧鐜夊６銆佸０鍔块渿澶╃殑澹附鏅鎵€闇囨捈锛屾彁绗斿啓涓嬩簡杩欓涓冨緥锛屼笉浠呯瑪鍔涢泟鍋ワ紝鑰屼笖鍏朵腑鈥滀簯闆炬鼎钂稿崕涓嶆敞锛屾尝婢滃０闇囧ぇ鏄庢箹鈥濅竴鑱旀洿鏄娴庡崡灞辨按鍏宠仈鐨勭粷濡欏啓鐓с€?, 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/audio/baotu_spring_zhao.mp3', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/video/baotu_spring_zhao.mp4', '["娓呬附", "璞斁", "鍐欐櫙"]'),
(5, '椴侀儭涓滅煶闂ㄩ€佹潨浜岀敨', '閱夊埆澶嶅嚑鏃ワ紝鐧讳复閬嶆睜鍙般€俓n浣曟椂鐭抽棬璺紝閲嶆湁閲戞ń寮€銆俓n绉嬫尝钀芥硹姘达紝娴疯壊鏄庡緜寰曘€俓n椋炶摤鍚勮嚜杩滐紝涓斿敖鎵嬩腑鏉€?, 1, 4, 4, '銆愰瞾閮°€戝嵆鍏栧窞锛屾不鎵€鍦ㄤ粖灞变笢鍏栧窞锛岃緰鏇查槣绛夊湴銆俓n銆愭硹姘淬€戞按鍚嶏紝娴佺粡鏇查槣銆佸厲宸炵瓑鍦般€俓n銆愬緜寰曘€戝北鍚嶏紝鍦ㄤ粖灞变笢娉板畨涓滃崡銆俓n銆愰钃€戜竴绉嶉殢椋庨鑽＄殑钃崏锛屾瘮娓稿瓙琛岃釜鏃犲畾銆?, '鍞愮巹瀹楀ぉ瀹濆洓杞斤紙745骞达級绉嬪ぉ锛屾潕鐧戒笌鏉滅敨鍦ㄩ綈椴佸ぇ鍦板悓娓哥粨鏉熴€傛潨鐢皢瑗垮幓闀垮畨锛屾潕鐧藉皢涓嬫睙涓溿€備袱浜哄湪椴侀儭涓滈潰鐨勭煶闂ㄥ北锛堜粖鏇查槣涓滃寳锛夊垎鎵嬶紝鏉庣櫧鍦ㄤ复鍒椂鍐欎笅杩欓璇椼€傝繖鏄袱浣嶄紵澶ц瘲浜烘枃瀛﹀彶涓婄殑鏈€鍚庝竴娆′細闈紝姝ゅ悗澶╁悇涓€鏂癸紝鍐嶆湭鐩歌銆?, 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/audio/shimen_send.mp3', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/video/shimen_send.mp4', '["璞斁", "娣辨儏", "鎯滃埆"]'),
(6, '鏌虫硥娑堝鏉傚拸', '涓€鏇叉竻娉夋暟琛屾煶锛岄棽涓秷澶忚儨浜庣銆俓n鏈堥粦蹇芥潵鏄熶竴鐐癸紝娴佽悿椋炰笂璇讳功鐏€?, 6, 8, 7, '銆愪竴鏇叉竻娉夋暟琛屾煶銆戞弿鍐欎簡鏌虫硥婧㈡按鎴愭邯銆佹煶鏍戠幆鎶辩殑骞介泤椋庡厜銆俓n銆愭祦钀ら涓婅涔︾伅銆戝啓澶滈噷璇讳功鏃讹紝钀ょ伀铏儚涓€棰楀井灏忕殑鏄熸槦涓€鏍烽钀藉湪涔︾伅涓婄殑缇庝附鐢婚潰锛岃〃鐜颁簡璇椾汉瀹夎传涔愰亾銆佹矇娴镐簬璇讳功鍐欎綔鐨勬竻闆呭績澧冦€?, '杩欓璇楀啓浜庤挷鏉鹃緞鐨勬晠涔℃穭鍗氭穭宸濊挷瀹跺簞銆傝挷鏉鹃緞鍦ㄦ煶娉夌晹缁撳簮璇讳功锛屽苟鍦ㄦ硥杈硅鑼舵嫑寰呰矾浜猴紝鎼滈泦濂囬椈寮備簨锛屾渶缁堝垱浣滀簡銆婅亰鏂嬪織寮傘€嬨€傛湰璇楃敓鍔ㄥ啀鐜颁簡浠栧湪鏌虫硥鐣旀秷澶忚涔︾殑闈欒哀姘涘洿銆?, 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/audio/liuquan_xiaoxia.mp3', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/video/liuquan_xiaoxia.mp4', '["鎭贰", "骞介潤", "鍐欏疄"]'),
(7, '闄粠绁栨祹鍗楀お瀹堟硾楣婂北婀栦笁棣栵紙鍏朵笁锛?, '姘村叆鍖楁箹鍘伙紝鑸熶粠鍗楁郸鍥炪€俓n閬ョ湅楣婂北杞紝鍗翠技閫佷汉鏉ャ€?, 1, 4, 2, '銆愰箠灞辨箹銆戝彜婀栧悕锛屽湪浠婃祹鍗楅箠灞变笅銆俓n銆愬寳婀栥€戞寚澶ф槑婀栧強浠ュ寳鐨勬按鍩熴€俓n銆愬崡娴︺€戞硾鎸囬€佸埆涔嬪湴鎴栧皬鐮佸ご銆?, '鍞愪唬澶╁疂骞撮棿锛屾潕鐧芥父鍘嗘祹鍗楁椂锛岄櫔鍚屼粬鐨勪粠绁栵紙鍫傜鐖讹紝鏃朵换娴庡崡澶畧锛変箻鑸熸父瑙堥箠灞辨箹锛堜粖娴庡崡澶ф槑婀栧強楣婂北涓€甯︼級锛屽啓涓嬩簡杩欓浜旇█缁濆彞銆傝瘲涓妸灞辨按鍊掕浆銆佽鑸熷椋炵殑鍔ㄦ劅鍐欏緱鏋佸叾绌虹伒锛屽睍鐜颁簡娴庡崡榛勬渤闄勮繎婀栧厜灞辫壊鐨勬竻绉€涔嬬編銆?, 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/audio/queshan_lake.mp3', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/video/queshan_lake.mp4', '["娓呮柊", "绌虹伒", "鍐欐櫙"]'),
(8, '灏嗚繘閰?, '鍚涗笉瑙侀粍娌充箣姘村ぉ涓婃潵锛屽娴佸埌娴蜂笉澶嶈繕銆俓n鍚涗笉瑙侀珮鍫傛槑闀滄偛鐧藉彂锛屾湞濡傞潚涓濇毊鎴愰洩銆俓n浜虹敓寰楁剰椤诲敖娆紝鑾娇閲戞ń绌哄鏈堛€俓n澶╃敓鎴戞潗蹇呮湁鐢紝鍗冮噾鏁ｅ敖杩樺鏉ャ€俓n鐑圭緤瀹扮墰涓斾负涔愶紝浼氶』涓€楗笁鐧炬澂銆俓n宀戝か瀛愶紝涓逛笜鐢燂紝灏嗚繘閰掞紝鏉帿鍋溿€俓n涓庡悰姝屼竴鏇诧紝璇峰悰涓烘垜鍊捐€冲惉銆俓n閽熼紦棣旂帀涓嶈冻璐碉紝浣嗘効闀块唹涓嶅閱掋€俓n鍙ゆ潵鍦ｈ搐鐨嗗瘋瀵烇紝鎯熸湁楗€呯暀鍏跺悕銆俓n闄堢帇鏄旀椂瀹村钩涔愶紝鏂楅厭鍗佸崈鎭ｆ璋戙€俓n涓讳汉浣曚负瑷€灏戦挶锛屽緞椤绘步鍙栧鍚涢厡銆俓n浜旇姳椹紝鍗冮噾瑁橈紝\n鍛煎効灏嗗嚭鎹㈢編閰掞紝涓庡皵鍚岄攢涓囧彜鎰併€?, 1, 4, 5, '銆愬ぉ涓婃潵銆戞寚榛勬渤鍙戞簮浜庢瀬楂樼殑楂樺師锛屾皵鍔跨绀达紝瀹涘浠庡ぉ鑰岄檷銆俓n銆愬埌娴枫€戦粍娌虫祦缁忓北涓滐紝娉ㄥ叆娓ゆ捣銆俓n銆愬矐澶瓙銆戝矐鍕嬶紝鏉庣櫧濂藉弸銆俓n銆愪腹涓樼敓銆戝厓涓逛笜锛屾潕鐧藉ソ鍙嬶紝闅愬＋銆俓n銆愰挓榧撻鐜夈€戝舰瀹瑰瘜璐典汉瀹剁殑濂㈠崕鐢熸椿銆?, '銆婂皢杩涢厭銆嬬害鍒涗綔浜庡攼澶╁疂鍗佷竴骞达紙752骞达級宸﹀彸銆傚綋鏃舵潕鐧戒笌濂藉弸鍏冧腹涓樸€佸矐鍕嬪湪棰嶉槼鑱氫細銆傛潕鐧芥鏃跺凡琚帓鎸ゅ嚭闀垮畨鏁板勾锛屾斂娌绘姳璐熸棤娉曟柦灞曪紝婊℃€€鎬€鎵嶄笉閬囩殑鎮叉劋锛屽€熼厭鍏村啓涓嬩簡杩欓姘斿悶灞辨渤鐨勫崈鍙ゆ澃浣溿€傚紑澶粹€滃娴佸埌娴蜂笉澶嶈繕鈥濆舰璞″湴姒傛嫭浜嗛粍娌虫渶缁堝湪灞变笢娉ㄥ叆澶ф捣鐨勫．闃斿巻绋嬨€?, 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/audio/qiangjinjiu.mp3', 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/video/qiangjinjiu.mp4', '["璞斁", "鎮插．", "娲掕劚"]');

-- 4. Events
INSERT INTO event (id, title, description, dynasty_id, year, significance, image_url) VALUES
(1, '鏉庢潨榻愰瞾鐩镐細', '澶╁疂涓夎浇锛?44骞达級鑷冲ぉ瀹濆洓杞斤紙745骞达級锛屸€滆瘲浠欌€濇潕鐧戒笌鈥滆瘲鍦ｂ€濇潨鐢湪娲涢槼鐩歌瘑鍚庯紝鍚屾父姊佸畫锛堜粖娌冲崡寮€灏併€佸晢涓橈級锛屽苟鍏堝悗涓ゆ鏉ュ埌灞变笢榻愰瞾澶у湴銆備粬浠悓娓告祹鍗楀ぇ鏄庢箹銆佹嘲灞便€佹硹姘寸瓑鍦帮紝鎼烘墜鐧婚珮銆侀ギ閰掕祴璇楋紝搴﹁繃浜嗕竴娈电湡鎸氱殑鏂囧浜ゆ父鏃跺厜銆傛渶缁堝湪鏇查槣涓滅煶闂ㄥ北渚濅緷鎯滃埆銆?, 4, 745, '涓浗鏂囧鍙蹭笂鏈€浼熷ぇ鐨勫弻瀛愭槦鐨勭浉閬囦笌鍚屾父锛屼唬琛ㄤ簡鐩涘攼姘旇薄涓嬫枃浜轰氦寰€鐨勫穮宄帮紝鐣欎笅浜嗐€婇瞾閮′笢鐭抽棬閫佹潨浜岀敨銆嬨€併€婇櫔鏉庡寳娴峰鍘嗕笅浜€嬬瓑浼犱笘鍚嶇瘒锛屽灞变笢娈甸粍娌虫祦鍩熺殑鏂囧鍦版爣鏋勫缓鍏锋湁濂犲熀鎬ф剰涔夈€?, 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/events/lidu_meeting.jpg'),
(2, '璧靛瓱闋嚭浠绘祹鍗楁€荤', '鍏冧笘绁栬嚦鍏冧簩鍗佷節骞达紙1292骞达級锛岃憲鍚嶄功鐢诲璧靛瓱闋嚭浠诲悓鐭ユ祹鍗楄矾鎬荤搴滀簨銆傚湪浠讳笁骞存湡闂达紝浠栨繁鍏ヨ€冨療娴庡崡鐨勫北宸濇硥姘达紝鍐欎笅浜嗐€婅兜绐佹硥銆嬬瓑鎻忕粯娉夊煄椋庡厜鐨勮瘲姝屻€傚苟鍦ㄧ浠诲悗鏍规嵁璁板繂缁樺埗浜嗕腑鍥借壓鏈彶涓婅憲鍚嶇殑銆婇箠鍗庣鑹插浘銆嬶紝灞曠幇娴庡崡楣婂北鍜屽崕涓嶆敞灞变竴甯︾殑娓呬附椋庡厜銆?, 6, 1292, '鏋佸ぇ鍦版彁鍗囦簡娴庡崡娉夋按涓庡北姘村湪鍏ㄥ浗鏂囧鑹烘湳鐣岀殑鍦颁綅锛屽叾鍒涗綔鐨勩€婇箠鍗庣鑹插浘銆嬪拰璇楁瓕鎴愪负娴庡崡鏈€鍏锋爣蹇楁€х殑鑹烘湳鏂囧寲鍚嶇墖涔嬩竴銆?, 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/events/zhao_jinan.jpg'),
(3, '钂叉澗榫勬煶娉夎鑼堕噰椋?, '娓呭悍鐔欏勾闂达紝钂叉澗榫勫湪鏁呬埂娣勫窛锛堜粖娣勫崥甯傛穭宸濆尯锛夌殑鏌虫硥锛堝張绉版弧浜曪級鏃佽绔嬭寘浜紝涓鸿繃寰€琛屼汉鍏嶈垂鎻愪緵鑼舵按锛屽彧姹傝矾浜鸿杩板惉闂荤殑姘戦棿鎬紓鏁呬簨鎴栦紶璇淬€備粬浠ユ绉疮浜嗗ぇ閲忕殑鍒涗綔绱犳潗锛屽苟鍦ㄥ叾鈥滆亰鏂嬧€濅腑鎸戠伅澶滄垬锛屽巻鏃舵暟鍗佸勾鍒涗綔鍑轰腑鍥芥枃瑷€灏忚宸呭嘲涔嬩綔銆婅亰鏂嬪織寮傘€嬨€?, 8, 1679, '寮€鍚簡涓浗鍙ゅ吀鏂囧鍙蹭笂鐙壒鐨勨€滄皯闂撮噰椋庘€濅笌鈥滄枃浜哄啀鍒涗綔鈥濇ā寮忥紝浣挎穭鍗氭煶娉夋垚涓鸿亰鏂嬫枃鍖栫殑鏍稿績鍙戞簮鍦帮紝鏋勫缓浜嗘瀬鍏烽瞾涓壒鑹茬殑绁炵娴极鏂囧鏅銆?, 'https://shandong-lit-landscape.oss-cn-beijing.aliyuncs.com/events/pu_gathering.jpg');

-- 5. Poem-Event Relations
INSERT INTO poem_event (poem_id, event_id) VALUES
(1, 1), -- 銆婃湜宀炽€?-> 鏉庢潨榻愰瞾鐩镐細
(2, 1), -- 銆婇櫔鏉庡寳娴峰鍘嗕笅浜€?-> 鏉庢潨榻愰瞾鐩镐細
(4, 2), -- 銆婅兜绐佹硥銆嬶紙璧靛瓱闋級 -> 璧靛瓱闋嚭浠绘祹鍗楁€荤
(5, 1), -- 銆婇瞾閮′笢鐭抽棬閫佹潨浜岀敨銆?-> 鏉庢潨榻愰瞾鐩镐細
(6, 3); -- 銆婃煶娉夋秷澶忔潅鍜忋€?-> 钂叉澗榫勬煶娉夎鑼堕噰椋?
